name: Python App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run script
        run: |
          python main.py

      - name: Archive files
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: main.py
